### ISSUE TITLE
SSL connections

### ISSUE THREAD

**Issue by jferdelyi** [3ddelano/mongo-driver-godot#2]
Hello, I would like to know if there are any plans to add the ability to make encrypted connections?

It doesn't seem complicated: https://mongocxx.org/mongocxx-v3/configuration/

Really nice job by the way !

**Comment by 3ddelano** [comment]
This is already supported. You can pass the TLS options to the URI in the `MongoDrive.connect_to_server` method as query strings. For example:

```GDScript
var cert_path = ProjectSettings.globalize_path("res://mycert.pem")
var uri = "mongodb://host1/?tls=true&tlsAllowInvalidCertificates=true&tlsCAFile='%s'" % cert_path
var driver = MongoDriver.new()
var connection = driver.connect_to_server(uri)
```

**Comment by jferdelyi** [comment]
Ho ok sorry for that, thank you
